name: "Comprueba el envío de objetivos"
on:
  pull_request:
    paths:
      - 'objetivos/*'

jobs:
  user_story_check:
    runs-on: ubuntu-latest
    steps:
      - name: Extrae URL del repositorio
        uses: JJ/github-pr-contains-action@releases/v2
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: Busca historias de usuario
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const diff = process.env.diff
            console.log( diff )
            console.log( context )
            const ficheroObjetivosMatch = /objetivos\/(.+?)\.md)/.exec(diff)
            if  ( ficheroObjetivosMatch === null ) {
                core.setFailed("❌ No hay fichero de objetivos enviado")
            } else {
                const user = ficheroObjetivosMatch[1] // segundo resultado
                if ( user !== context.actor ) {
                    core.setFailed("❌ El fichero de objetivos enviado " + user + ".md no corresponde a " + context.actor)
                }
            }

