name: "Comprueba cómo se han cerrado los issues"
on:
  pull_request:
    paths:
      - 'proyectos/hito-[34567].md'

jobs:
  closing_issue_check:
    runs-on: ubuntu-latest
    steps:
      - name: Extrae URL del repositorio
        uses: JJ/github-pr-contains-action@releases/v2
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: Extrae usuario y nombre del repo
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const diff = process.env.diff;
            const ghRepoMatch = /github.com\/(\S+)\/(.+?)(:\s+|\))/.exec(diff)
            if  ( ghRepoMatch === null ) {
                core.setFailed("❌ There's no repo URL in this diff with required format")
            } else {
                const user = ghRepoMatch[1] // segundo resultado
                const repo = ghRepoMatch[2] // tercer resultado
                console.log( "» Encontrado repo " + repo + " para usuario " + user )
                core.exportVariable('user',user)
                core.exportVariable('repo',repo)
            }

      - name: Ejecuta contenedor
        uses: ${{env.user}}/${{env.repo}}
