name: "Comprueba el estado de la IC"
on:
  pull_request:
    paths:
      - 'proyectos/hito-[3567].md'

jobs:
  CI_status_check:
    runs-on: ubuntu-latest
    steps:
      - name: Extrae URL del repositorio
        uses: JJ/github-pr-contains-action@releases/v2
        with:
          github-token: ${{github.token}}
          filesChanged: 1
      - name: Hace comprobaciones
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const diff = process.env.diff;
            const ghRepoMatch = /github.com\/(\S+)\/(.+?)(:\s+|\))/.exec(diff)
            if  ( ghRepoMatch === null ) {
                core.setFailed("❌ No hay ningún URL de un repositorio con el formato requerido en el diff")
            } else {
                const user = ghRepoMatch[1] // segundo resultado
                const repo = ghRepoMatch[2] // tercer resultado
                console.log( "» Analizando repo " + repo + " del usuario 🔥" + user )
                const checks_before_pag = await github.checks.listForRef.endpoint.merge( { owner: user, repo: repo, ref: 'HEAD', status: 'completed' })
                const checks = await github.paginate( checks_before_pag)
                console.log( "✅ Hay " + checks.length + " sistemas de CI configurados")

                if ( checks.length < 2 ) {
                    core.setFailed("❌ No hay al menos dos sistemas de CI configurados")
                }
                const green_checks = checks.filter( check => check.conclusion === "success" )
                if ( !green_checks.length ) {
                    core.setFailed("❌ No hay al menos un CI que esté en verde")
                } else {
                    console.log( "✅ Hay " + green_checks.length + " que pasan los tests correctamente" )
                }
                if ( ! green_checks.filter( check => check.app.slug === "travis-ci" ) ) {
                    core.setFailed("❌ Travis está fallando en este momento")
                } else {
                    console.log( "✅ Entre ellos está Travis" )
                }
            }

